### PR TITLE
New build system

### PR DESCRIPTION
**Pull request by cstich**
Hi,

I am not sure you will like this too much but I thought I would try nevertheless. I updated your slides slightly but the main difference is the new build system I found (we have to attribute this, if you go ahead with this pull request). Basically you can have notes next to your slides now, which I found really handy. The [mtheme](https://github.com/matze/mtheme) becomes a dependency but it is easy enough to drop that. I just thought it looks much prettier ;-)

Let me know what you think
Cheers,
C.

### CODE REVIEW

**Comment by darribas** [comment]
Very cool. Would the html be rendered directly if I merge this?

**Comment by cstich** [comment]
I didn't care about HTML right now, but I think I should be able to add an option to the makefile. I am not a 100 percent sure what would happen to the notes though. I have to check this out.

**Comment by darribas** [comment]
I'd like it to stay live on the HTML as it's very handy. Although since I pinned my version, we could just have this evolve in whichever way it goes, with or without html.

**Comment by cstich** [comment]
I added HTML support to the build system now. I couldn't figure out how to keep the latex notes in the HTML. Also admittedly the HTML could probably use a bit more "styling". At the moment it is very bare-metal, but it works.

**Comment by darribas** [comment]
Right, but the HTML are not slides, correct?

**Comment by cstich** [comment]
No, the HTML are not slides yet. How have you compiled your slides to HTML so far?

**Comment by darribas** [comment]
For this I originally used RStudio to convert them into reveal.js. But under the hood it's using pandoc, so you can look at that too.

**Pull request closed without merging**
